/// Bundled skill files embedded at compile time.
/// Tuples of (relative_path_from_skills_dir, file_content).
/// Written to `~/.rushdino/skills/` on first run via `ensure_rushdino_dir_at`.
pub const BUNDLED_SKILL_FILES: &[(&str, &str)] = &[
    (
        "skill-creator/SKILL.md",
        include_str!("skills/skill-creator/SKILL.md"),
    ),
    (
        "skill-creator/agents/grader.md",
        include_str!("skills/skill-creator/agents/grader.md"),
    ),
    (
        "skill-creator/agents/comparator.md",
        include_str!("skills/skill-creator/agents/comparator.md"),
    ),
    (
        "skill-creator/agents/analyzer.md",
        include_str!("skills/skill-creator/agents/analyzer.md"),
    ),
    (
        "skill-creator/assets/eval_review.html",
        include_str!("skills/skill-creator/assets/eval_review.html"),
    ),
    (
        "skill-creator/eval-viewer/generate_review.py",
        include_str!("skills/skill-creator/eval-viewer/generate_review.py"),
    ),
    (
        "skill-creator/eval-viewer/viewer.html",
        include_str!("skills/skill-creator/eval-viewer/viewer.html"),
    ),
    (
        "skill-creator/references/schemas.md",
        include_str!("skills/skill-creator/references/schemas.md"),
    ),
    (
        "skill-creator/scripts/aggregate_benchmark.py",
        include_str!("skills/skill-creator/scripts/aggregate_benchmark.py"),
    ),
    (
        "skill-creator/scripts/generate_report.py",
        include_str!("skills/skill-creator/scripts/generate_report.py"),
    ),
    (
        "skill-creator/scripts/improve_description.py",
        include_str!("skills/skill-creator/scripts/improve_description.py"),
    ),
    (
        "skill-creator/scripts/package_skill.py",
        include_str!("skills/skill-creator/scripts/package_skill.py"),
    ),
    (
        "skill-creator/scripts/quick_validate.py",
        include_str!("skills/skill-creator/scripts/quick_validate.py"),
    ),
    (
        "skill-creator/scripts/run_eval.py",
        include_str!("skills/skill-creator/scripts/run_eval.py"),
    ),
    (
        "skill-creator/scripts/run_loop.py",
        include_str!("skills/skill-creator/scripts/run_loop.py"),
    ),
    (
        "skill-creator/scripts/utils.py",
        include_str!("skills/skill-creator/scripts/utils.py"),
    ),
];
