[package]
name = "rushdino-discord"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
tokio.workspace = true
tracing.workspace = true
serenity = { version = "0.12", default-features = false, features = ["client", "gateway", "model", "rustls_backend"] }
rushdino-common = { path = "../../common" }
rushdino-gateway = { path = "../../gateway" }
